### ISSUE TITLE
Create form submission form

### ISSUE THREAD

**Issue by arantespp** [TriangulosTecnologia/lps#4]
### Description

Create the form submission page as we can see on [Figma](https://www.figma.com/file/4YcN9TNkYF4rH7aha1aNOY/Simulare?node-id=546%3A696).

![image](https://user-images.githubusercontent.com/16626980/126200166-447d9e2a-00d5-4521-a168-f3bd6880dc7f.png)

#### Tasks

- [x] Implement the page with responsiveness.
- [x] Create form validations in case the user forgot to input some data.
- [x] Implement navigation buttons.
- [x] #9 
- [x] [Fix forward ref warning](https://github.com/TriangulosTecnologia/lps/issues/4#issuecomment-884623930).

**Comment by arantespp** [comment]
We're getting an error relative to React.forwardRef(). We have two ways to fix this problem:

1. Wrap to `React.forwardRef()` on the `Input` component or;
2. Remove `Input` component and [style input on theme](https://theme-ui.com/components/input).

![image](https://user-images.githubusercontent.com/16626980/126583949-19295a3c-c05b-4ea0-a475-a0898c20e54d.png)
